"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.model_source_enum import ModelSourceEnum
globals()['ModelSourceEnum'] = ModelSourceEnum
from bimdata_api_client.model.model_request import ModelRequest


class TestModelRequest(unittest.TestCase):
    """ModelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRequest(self):
        """Test ModelRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
