"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.folder_without_children import FolderWithoutChildren
from bimdata_api_client.model.group import Group
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['FolderWithoutChildren'] = FolderWithoutChildren
globals()['Group'] = Group
from bimdata_api_client.model.group_folder import GroupFolder


class TestGroupFolder(unittest.TestCase):
    """GroupFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupFolder(self):
        """Test GroupFolder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupFolder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
