"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.model_status_enum import ModelStatusEnum
globals()['ModelStatusEnum'] = ModelStatusEnum
from bimdata_api_client.model.processor_handler import ProcessorHandler


class TestProcessorHandler(unittest.TestCase):
    """ProcessorHandler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorHandler(self):
        """Test ProcessorHandler"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorHandler()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
