"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
globals()['FolderPermissionEnum'] = FolderPermissionEnum
from bimdata_api_client.model.patched_group_folder_request import PatchedGroupFolderRequest


class TestPatchedGroupFolderRequest(unittest.TestCase):
    """PatchedGroupFolderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedGroupFolderRequest(self):
        """Test PatchedGroupFolderRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedGroupFolderRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
