"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.model_source_enum import ModelSourceEnum


class TestModelSourceEnum(unittest.TestCase):
    """ModelSourceEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelSourceEnum(self):
        """Test ModelSourceEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelSourceEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
