"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.cloud_role_enum import CloudRoleEnum
from bimdata_api_client.model.invitation_status_enum import InvitationStatusEnum
from bimdata_api_client.model.null_enum import NullEnum
from bimdata_api_client.model.project_role_enum import ProjectRoleEnum
globals()['CloudRoleEnum'] = CloudRoleEnum
globals()['InvitationStatusEnum'] = InvitationStatusEnum
globals()['NullEnum'] = NullEnum
globals()['ProjectRoleEnum'] = ProjectRoleEnum
from bimdata_api_client.model.invitation import Invitation


class TestInvitation(unittest.TestCase):
    """Invitation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitation(self):
        """Test Invitation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Invitation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
