"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.group import Group
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['Group'] = Group
from bimdata_api_client.model.folder_group_permission import FolderGroupPermission


class TestFolderGroupPermission(unittest.TestCase):
    """FolderGroupPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderGroupPermission(self):
        """Test FolderGroupPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderGroupPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
