"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.group_request import GroupRequest
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['GroupRequest'] = GroupRequest
from bimdata_api_client.model.folder_group_permission_request import FolderGroupPermissionRequest


class TestFolderGroupPermissionRequest(unittest.TestCase):
    """FolderGroupPermissionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderGroupPermissionRequest(self):
        """Test FolderGroupPermissionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderGroupPermissionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
