"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_group_permission import FolderGroupPermission
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.model_type_enum import ModelTypeEnum
from bimdata_api_client.model.nature_enum import NatureEnum
from bimdata_api_client.model.null_enum import NullEnum
from bimdata_api_client.model.recursive_folder_children_type_enum import RecursiveFolderChildrenTypeEnum
from bimdata_api_client.model.user import User
globals()['FolderGroupPermission'] = FolderGroupPermission
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['ModelTypeEnum'] = ModelTypeEnum
globals()['NatureEnum'] = NatureEnum
globals()['NullEnum'] = NullEnum
globals()['RecursiveFolderChildrenTypeEnum'] = RecursiveFolderChildrenTypeEnum
globals()['User'] = User
from bimdata_api_client.model.recursive_folder_children import RecursiveFolderChildren


class TestRecursiveFolderChildren(unittest.TestCase):
    """RecursiveFolderChildren unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecursiveFolderChildren(self):
        """Test RecursiveFolderChildren"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecursiveFolderChildren()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
