"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.nature_enum import NatureEnum


class TestNatureEnum(unittest.TestCase):
    """NatureEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNatureEnum(self):
        """Test NatureEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NatureEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
