"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.model_type_enum import ModelTypeEnum


class TestModelTypeEnum(unittest.TestCase):
    """ModelTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelTypeEnum(self):
        """Test ModelTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
