"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
globals()['FolderPermissionEnum'] = FolderPermissionEnum
from bimdata_api_client.model.patched_folder_without_children_request import PatchedFolderWithoutChildrenRequest


class TestPatchedFolderWithoutChildrenRequest(unittest.TestCase):
    """PatchedFolderWithoutChildrenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedFolderWithoutChildrenRequest(self):
        """Test PatchedFolderWithoutChildrenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedFolderWithoutChildrenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
