"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.document import Document
from bimdata_api_client.model.model_source_enum import ModelSourceEnum
from bimdata_api_client.model.model_type_enum import ModelTypeEnum
from bimdata_api_client.model.user import User
globals()['Document'] = Document
globals()['ModelSourceEnum'] = ModelSourceEnum
globals()['ModelTypeEnum'] = ModelTypeEnum
globals()['User'] = User
from bimdata_api_client.model.model import Model


class TestModel(unittest.TestCase):
    """Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel(self):
        """Test Model"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Model()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
