"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.model_status_enum import ModelStatusEnum
globals()['ModelStatusEnum'] = ModelStatusEnum
from bimdata_api_client.model.patched_processor_handler_request import PatchedProcessorHandlerRequest


class TestPatchedProcessorHandlerRequest(unittest.TestCase):
    """PatchedProcessorHandlerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedProcessorHandlerRequest(self):
        """Test PatchedProcessorHandlerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedProcessorHandlerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
