"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.group_folder_read import GroupFolderRead
from bimdata_api_client.model.light_document import LightDocument
from bimdata_api_client.model.short_user import ShortUser
globals()['GroupFolderRead'] = GroupFolderRead
globals()['LightDocument'] = LightDocument
globals()['ShortUser'] = ShortUser
from bimdata_api_client.model.edit_folder import EditFolder


class TestEditFolder(unittest.TestCase):
    """EditFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditFolder(self):
        """Test EditFolder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditFolder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
