"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.cloud_role_enum import CloudRoleEnum
globals()['CloudRoleEnum'] = CloudRoleEnum
from bimdata_api_client.model.cloud_role import CloudRole


class TestCloudRole(unittest.TestCase):
    """CloudRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRole(self):
        """Test CloudRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
