"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.project_status_enum import ProjectStatusEnum
globals()['ProjectStatusEnum'] = ProjectStatusEnum
from bimdata_api_client.model.patched_project_request import PatchedProjectRequest


class TestPatchedProjectRequest(unittest.TestCase):
    """PatchedProjectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedProjectRequest(self):
        """Test PatchedProjectRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedProjectRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
