"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.project_role_enum import ProjectRoleEnum
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['ProjectRoleEnum'] = ProjectRoleEnum
from bimdata_api_client.model.folder_user_project import FolderUserProject


class TestFolderUserProject(unittest.TestCase):
    """FolderUserProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderUserProject(self):
        """Test FolderUserProject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderUserProject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
