"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.folder_group_permission import FolderGroupPermission
from bimdata_api_client.model.folder_permission_enum import FolderPermissionEnum
from bimdata_api_client.model.user import User
globals()['FolderGroupPermission'] = FolderGroupPermission
globals()['FolderPermissionEnum'] = FolderPermissionEnum
globals()['User'] = User
from bimdata_api_client.model.folder_without_children import FolderWithoutChildren


class TestFolderWithoutChildren(unittest.TestCase):
    """FolderWithoutChildren unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderWithoutChildren(self):
        """Test FolderWithoutChildren"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderWithoutChildren()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
