"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.invitation_status_enum import InvitationStatusEnum


class TestInvitationStatusEnum(unittest.TestCase):
    """InvitationStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationStatusEnum(self):
        """Test InvitationStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvitationStatusEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
