version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  restore_cache: &restore_cache
    - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
            - v1-dependencies
jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  test:
    <<: *container_config

    steps:
      - *restore_repo
      - *restore_cache

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt
            pip install python-semantic-release
            pip install tox

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox
  release:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_cache
      - run:
        environment:
          GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1
        command: |
          . venv/bin/activate
          if [[ $GIT_COMMIT_DESC == \[PATCH\]* ]];
          then
            semantic-release publish --patch
          elif [[ $GIT_COMMIT_DESC == \[MINOR\]* ]];
          then
            semantic-release publish --minor
          elif [[ $GIT_COMMIT_DESC == \[MAJOR\]* ]];
          then
            semantic-release publish --major
          fi

workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          requires:
            - checkout_code
            - test
          filters:
            branches:
              only:
                - master
