version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  restore_env: &restore_env
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}-{{ checksum "ci-requirements.txt" }}
        - v1-dependencies

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  test:
    <<: *container_config

    steps:
      - *restore_repo
      - *restore_env

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt
            pip install -r ci-requirements.txt
            pip install tox

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}-{{ checksum "ci-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox
  release:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_env
      - run:
          environment:
            GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1
          command: |
            git config --global user.email "infra@bimdata.io"
            git config --global user.name "Circle CI"
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            . venv/bin/activate
            PYTHONPATH=/home/circleci/repo semantic-release publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          requires:
            - checkout_code
            - test
          filters:
            branches:
              only:
                - master
