# coding: utf-8

"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from bimdata_api_client.configuration import Configuration


class UserProject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'role': 'int',
        'user': 'User',
        'invitation': 'ProjectInvitation',
        'project': 'int'
    }

    attribute_map = {
        'role': 'role',
        'user': 'user',
        'invitation': 'invitation',
        'project': 'project'
    }

    def __init__(self, role=None, user=None, invitation=None, project=None, local_vars_configuration=None):  # noqa: E501
        """UserProject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._role = None
        self._user = None
        self._invitation = None
        self._project = None
        self.discriminator = None

        if role is not None:
            self.role = role
        if user is not None:
            self.user = user
        if invitation is not None:
            self.invitation = invitation
        self.project = project

    @property
    def role(self):
        """Gets the role of this UserProject.  # noqa: E501

        User's role in the project  # noqa: E501

        :return: The role of this UserProject.  # noqa: E501
        :rtype: int
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this UserProject.

        User's role in the project  # noqa: E501

        :param role: The role of this UserProject.  # noqa: E501
        :type: int
        """

        self._role = role

    @property
    def user(self):
        """Gets the user of this UserProject.  # noqa: E501


        :return: The user of this UserProject.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserProject.


        :param user: The user of this UserProject.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def invitation(self):
        """Gets the invitation of this UserProject.  # noqa: E501


        :return: The invitation of this UserProject.  # noqa: E501
        :rtype: ProjectInvitation
        """
        return self._invitation

    @invitation.setter
    def invitation(self, invitation):
        """Sets the invitation of this UserProject.


        :param invitation: The invitation of this UserProject.  # noqa: E501
        :type: ProjectInvitation
        """

        self._invitation = invitation

    @property
    def project(self):
        """Gets the project of this UserProject.  # noqa: E501


        :return: The project of this UserProject.  # noqa: E501
        :rtype: int
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this UserProject.


        :param project: The project of this UserProject.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and project is None:  # noqa: E501
            raise ValueError("Invalid value for `project`, must not be `None`")  # noqa: E501

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserProject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserProject):
            return True

        return self.to_dict() != other.to_dict()
