
name: Python API CLient

on: push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: pip install tox twine -r requirements.txt -r test-requirements.txt
      # Open-api-generator is broken. To be updated when upgrading
      # - name: test 
      #   run: tox
      - name: Check Readme syntax
        run: |
          python setup.py sdist
          twine check dist/*

  release:
    runs-on: self-hosted
    needs: test
    if: contains('
        refs/heads/master
        refs/heads/main'
      , github.ref)
    concurrency: release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_TOKEN }}
      